---
title: "Demuxlet"
output:
  html_document:
    theme: readable
    df_print: paged
    code_folding: hide
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(stringsAsFactors = F)
seed <- 87532163

library(knitr)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(scales)
library(glue)

# source("~/scripts/R_rainclouds.R")

knitr::opts_knit$set(root.dir = "/home/dricardo/work/2021_mgi_brains_pool1")
knitr::opts_chunk$set(fig.width = 4, fig.height = 4, fig.show = "hold")

options(dplyr.summarise.inform = FALSE)  # Disable "`summarise()` has grouped output by 'foo'" message

theme_set(theme_bw(base_size = 12))
```

```{r}
demux <- read.table(
  "work/demuxlet/output_by_batch/demux_batch.7_16.best", header = T, sep ="\t"
) %>% 
  mutate(call = gsub("-.*", "", BEST))
```

```{r}
demux %>% 
  ggplot(aes(x = N.SNP)) +
  geom_histogram()

demux %>% 
  filter(call == "SNG") %>% 
  ggplot(aes(x = N.SNP)) +
  geom_histogram()

demux %>% 
  ggplot(aes(x = call, y = N.SNP)) +
  geom_boxplot()
```


```{r}
demux %>% 
  ggplot(aes(x = PRB.SNG1)) +
  geom_histogram()

demux %>% 
  ggplot(aes(x = PRB.DBL)) +
  geom_histogram()

demux %>% 
  ggplot(aes(x = PRB.SNG1, y = PRB.DBL)) +
  geom_point()
```

