---
title: "Seurat first-pass"
output:
  html_document:
    theme: readable
    df_print: paged
    code_folding: hide
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(stringsAsFactors = F)
seed <- 87532163

library(knitr)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(scales)
library(glue)

library(SoupX)
library(Matrix)
library(Seurat)

# source("~/scripts/R_rainclouds.R")

knitr::opts_knit$set(root.dir = "/home/dricardo/work/2021_mgi_brains_pool1")
knitr::opts_chunk$set(fig.width = 4, fig.height = 4, fig.show = "hold")

options(dplyr.summarise.inform = FALSE)  # Disable "`summarise()` has grouped output by 'foo'" message

theme_set(theme_bw(base_size = 12))
```

```{r}
sobj <- readRDS("/home/bnovotny/single_nuclei/pilot_integration/data/full_obj_123.rds")

sobj <- RunPCA(sobj)
sobj <- RunUMAP(sobj, dims = 1:10)
sobj <- FindNeighbors(sobj, dims = 1:10)
sobj <- FindClusters(sobj)
```

```{r, fig.width=5}
DimPlot(sobj, label = T) + NoLegend()
```

```{r, fig.width=8}
DimPlot(sobj, group.by = "orig.ident") + NoLegend() +
  facet_wrap(~ orig.ident)
```




```{r, fig.width=8}
1:2 %>% 
  lapply(function(i) {
    sobjs[[i]]@meta.data %>% 
      count(seurat_clusters, primary_sample) %>% 
      group_by(seurat_clusters) %>% 
      mutate(frac = n / sum(n)) %>% 
      ungroup() %>% 
      ggplot(aes(x = seurat_clusters, y = frac, fill = primary_sample)) +
      geom_col() +
      scale_fill_brewer(palette = "Set1") +
      labs(x = "Cluster", y = "Fraction", fill = "Sample") +
      ggtitle(glue("Pool {i}"))
  })
```

```{r, fig.height=6, fig.width=24}
marker_genes <- list(
  OPCs = c(
    'TNR','PDGFRA', 'CNTN1',
    "LHFPL3", "PCDH15"
    ),
  Oligos = c(
    'QDPR','TULP4','PIP4K2A','TMEM144','SLC44A1','CNP','SLAIN1','ANLN','MOBP',
    'SCD','CNDP1','MBP','ERMN','CLDND1','UGT8','TTLL7','SLC24A2','ENPP2','TF',
    'PLP1',
    "MOG",'OPALIN','SEPT4'
    ), 
  Neurons = c(  
    'PCLO','GABRA1','SCG2','UCHL1','GABRB2','GAD1','VSNL1','STMN2','RTN1',
    'SNAP25','SYT1','SCN2A','DLX6-AS1','SYNPR',
    'CNR1','RELN'
    ), 
  Neurons_exc = c(
    "RALYL", "KCNIP4", "CBLN2", "LDB2", "KCNQ5", "SATB2"
    # "SCL17A7"  Not present in the 67-brain data 
  ),
  Neurons_inh = c(
    "NXPH1", "GRIK1", "ADARB2", "GAD2"
    # "LHFPL3", "PCDH15" These are more OPC https://doi.org/10.1016/j.cell.2020.06.027
  ),
  Microglia = c(
    'C3','CCL4','MSR1','OLR1','GPR183','CD53','LCP1','HAVCR2','LHFPL2','PLEK',
    'HLA-DRA','CD74','CX3CR1','C3AR1','CLEC7A','B3GNT5',
    'CD83','IL1B','CH25H',
    "CSF1R", "P2RY12"
    ),
  Endothelial = c(
    'NET1','FN1','APOLD1','TM4SF1','ABCG2','RGS5','DCN',
    "VWF"
  ),
  Astrocytes = c(
    'SLCO1C1','ATP1B2','CPE','AQP4','EDNRB','SLC4A4','GJA1','SLC1A2','CLU',
    'ETNPPL','F3','RYR3',
    'DIO2','GPR37L1',
    "PDGFRA", # Also in OPCs
    "CSPG4", "GFAP"
  ),
  T_cell = c("PTPRC", "CD247", "CD3G", "GZMA"),
  B_cell = c("MS4A1"),
  Monocyte = c("CD68")
)

DotPlot(sobj, features = unlist(marker_genes) %>% unique(), col.min = 0, 
        assay = "SCT") + 
  RotatedAxis()
DotPlot(sobj, features = unlist(marker_genes) %>% unique(), col.min = 0, 
        assay = "integrated") + 
  RotatedAxis()
```

```{r, fig.height=6, fig.width=7}
marker_genes %>% 
  names() %>% 
  lapply(function(i) {
    DotPlot(sobjs[[1]], features = marker_genes[[i]], col.min = 0) + 
      RotatedAxis() +
      ggtitle(glue("Pool1: {i}"))    
  })
```

```{r}
clus_ids <- sobjs[[1]]@meta.data$seurat_clusters %>% as.character()
sobjs[[1]]@meta.data$celltypes <- case_when(
  clus_ids %in% as.character(15) ~ "OPC",
  clus_ids %in% as.character(c(6, 8)) ~ "Oligos", 
  clus_ids %in% as.character(c(0:5, 10:11, 13)) ~ "Neuron_exc",
  clus_ids %in% as.character(c(7, 9, 15, 16)) ~ "Neuron_inh",
  clus_ids %in% as.character(c(14)) ~ "MG-Endo", 
  clus_ids %in% as.character(c(17)) ~ "MG", 
  clus_ids %in% as.character(c(18, 12)) ~ "Astro", 
  T ~ clus_ids
)
```

```{r, fig.height=6, fig.width=7}
marker_genes %>% 
  names() %>% 
  lapply(function(i) { 
    DotPlot(sobjs[[2]], features = marker_genes[[i]], col.min = 0) + 
      RotatedAxis() +
      ggtitle(glue("Pool2: {i}"))    
  })
```

```{r}
clus_ids <- sobjs[[2]]@meta.data$seurat_clusters %>% as.character()
sobjs[[2]]@meta.data$celltypes <- case_when(
  clus_ids %in% as.character(16) ~ "OPC",
  clus_ids %in% as.character(c(0, 1, 8, 13)) ~ "Oligos", 
  clus_ids %in% as.character(c(2:6, 9, 10)) ~ "Neuron_exc",
  clus_ids %in% as.character(c(7, 12, 16, 17)) ~ "Neuron_inh",
  clus_ids %in% as.character(c(18)) ~ "MG", 
  clus_ids %in% as.character(c(19)) ~ "Endo", 
  clus_ids %in% as.character(c(11, 15)) ~ "Astro", 
  T ~ clus_ids
)
```

```{r, fig.width=5}
1:2 %>% 
  lapply(function(i) {
    sobj <- sobjs[[i]]
    Idents(sobj) <- "celltypes"
    DimPlot(sobj, label = TRUE) + NoLegend() +
      ggtitle(glue("Pool {i}"))
  })
```