---
title: "Seurat first-pass"
output:
  html_document:
    theme: readable
    df_print: paged
    code_folding: hide
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(stringsAsFactors = F)
seed <- 87532163

library(knitr)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(scales)
library(glue)

library(SoupX)
library(Matrix)
library(Seurat)

# source("~/scripts/R_rainclouds.R")

knitr::opts_knit$set(root.dir = "/home/dricardo/work/2021_mgi_brains_pool1")
knitr::opts_chunk$set(fig.width = 4, fig.height = 4, fig.show = "hold")

options(dplyr.summarise.inform = FALSE)  # Disable "`summarise()` has grouped output by 'foo'" message

theme_set(theme_bw(base_size = 12))
```

```{r}
qc <- data.table::fread("work/seurat/barcode_metrics.tsv.gz", header = T, data.table = F) %>% 
  mutate(barcode  = case_when(pool == "pool2" ~ gsub("-1$", "-2", barcode), 
                              T ~ barcode)) 
```

```{r}
demux <- lapply(1:16, function(i) {
  read.table(
    glue("work/demuxlet_rm_singletons_only/output_by_batch/demux_batch.{i}_16.best"), header = T, sep ="\t"
  )
}) %>% 
  bind_rows() %>% 
  mutate(pool = "pool1") %>% 
  rename(barcode = BARCODE)

demux2 <- lapply(1:14, function(i) {
  read.table(
    glue("../2021_mgi_brains_pool2/work/demuxlet_rm_singletons_only/output_by_batch/demux_batch.{i}_14.best"), 
    header = T, sep ="\t"
  )
}) %>% 
  bind_rows() %>% 
  mutate(pool = "pool2") %>% 
  rename(barcode = BARCODE) %>% 
  mutate(barcode = gsub("-1$", "-2", barcode))

demux <- bind_rows(demux, demux2) %>% 
  select(barcode, pool, BEST) %>% 
  mutate(demuxlet_call = gsub("-.*", "", BEST)) %>% 
  mutate(primary_sample = gsub("\\^.*", "", BEST)) %>% 
  mutate(primary_sample = gsub(".*-", "", primary_sample)) %>% 
  mutate(primary_sample = case_when(demuxlet_call != "SNG" ~ demuxlet_call, 
                                    T ~ primary_sample))
rm(demux2)

write.table(demux, file = "data/demuxlet_assignmnents.tsv", col.names = T, 
            row.names = F, sep = "\t", quote = F)
```

```{r}
md <- qc %>% 
  inner_join(demux, by = c("barcode", "pool")) %>% 
  filter(nUMI > 1000, pctMT < 0.2, cellranger_nuclei, demuxlet_call == "SNG")
rownames(md) <- md$barcode

barcodes_to_keep <- md$barcode

table(qc$barcode %in% barcodes_to_keep, qc$pool)
```

```{r}
indir1 <- "work/cellranger_gex/outs"
indir2 <- file.path("../2021_mgi_brains_pool2", indir1)

read_raw_counts <- function(indir, suffix) {
  indir <- file.path(indir, suffix)
  bc <- read.table(file.path(indir, "barcodes.tsv.gz"))[,1]
  features <- read.table(file.path(indir, "features.tsv.gz"))[,2]
  mat <- readMM(file.path(indir, "matrix.mtx.gz"))
  colnames(mat) <- bc
  rownames(mat) <- features
  return(mat)
}

m1_raw <- read_raw_counts(indir1, "raw_feature_bc_matrix")
m1_filt <- read_raw_counts(indir1, "filtered_feature_bc_matrix")
m2_raw <- read_raw_counts(indir2, "raw_feature_bc_matrix")
m2_filt <- read_raw_counts(indir2, "filtered_feature_bc_matrix")
```

```{r}
make_soupchannel <- function(m_raw, m_filt) {
  m_raw <- m_raw[which(rownames(m_raw) %in% rownames(m_filt)), ]
  rownames(m_raw) <- paste(rownames(m_raw), 1:nrow(m_raw), sep = "__")
  rownames(m_filt) <- paste(rownames(m_filt), 1:nrow(m_filt), sep = "__")
  sc <- SoupChannel(m_raw, m_filt)
  return(sc)
}

sc <- make_soupchannel(m1_raw, m1_filt)
```


```{r}
m1 <- m1_filt[, which(colnames(m1_filt) %in% barcodes_to_keep)]
m2 <- m2_filt
colnames(m2) <- gsub("-1$", "-2", colnames(m2))
m2 <- m2[, which(colnames(m2) %in% barcodes_to_keep)]

# m_list <- list(pool1 = m1, pool2 = m2)
# 
# saveRDS(m_list, file = "share/pool1-2_mats.filtered.rds")

dim(m1)
dim(m2)
```

```{r}
# sobjs <- list(m1, m2) %>%
#   lapply(function(i) {
#     sobj <- CreateSeuratObject(counts = i, meta.data = md)
#     sobj <- PercentageFeatureSet(sobj, pattern = "^MT-", col.name = "percent.mt")
#     sobj <- suppressWarnings(SCTransform(sobj, vars.to.regress = "percent.mt"))
#     sobj <- RunPCA(sobj)
#     sobj <- RunUMAP(sobj, dims = 1:30)
#     sobj <- FindNeighbors(sobj, dims = 1:30)
#     sobj <- FindClusters(sobj)
#   })
# 
# saveRDS(sobjs, file = "work/seurat/preprocessed_sobjs.rds")
# saveRDS(sobjs, file = "work/seurat/preprocessed_sobjs.no_dbls.rds")
sobjs <- readRDS("work/seurat/preprocessed_sobjs.no_dbls.rds")
names(sobjs) <- c("pool1", "pool2")

sobjs
```

# Look at PC correlation with tech. metrics
```{r, fig.width=8}
plot_pca_corr <- function(sobj) {
  emb <- Embeddings(sobj, reduction = "pca") %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column("barcode") %>% 
    left_join(sobj@meta.data, by = "barcode") %>% 
    {
      # One-hot encode sample IDs with model.matrix
      tmp <- model.matrix(barcode ~ primary_sample, data = .)
      tmp <- tmp[, -1] %>% 
        as.data.frame()
      # Combine temporary object and output
      cbind(., tmp)
    } %>% 
    select(-primary_sample) %>% 
    select(nCount_RNA, nFeature_RNA, nUMI, pctMT, starts_with("primary_sample"), PC_1:PC_50) %>% 
    gather("pc", "pc_val", starts_with("PC_")) %>% 
    gather("metric", "val_metric", nCount_RNA:pctMT, starts_with("primary_sample")) %>% 
    group_by(pc, metric) %>% 
    summarise(cor = cor(pc_val, val_metric, method = "s")) %>% 
    mutate(pc = factor(gsub("PC_", "", pc), levels = 1:50)) %>% 
    mutate(metric = gsub("primary_sample", "", metric))
  emb %>% 
    ggplot(aes(x = pc, y = metric, fill = cor)) +
    geom_tile(color = "gray") +
    scale_fill_distiller(palette = "RdBu", limits = c(-.7,.7)) +
    labs(x = "PC", y = "Metric", fill = "Spearman") +
    theme(axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1)) 
}

lapply(sobjs, plot_pca_corr)
```

```{r}
sobjs <- sobjs %>% 
  lapply(function(sobj) {
    sobj <- RunUMAP(sobj, dims = 2:10)
    sobj <- FindNeighbors(sobj, dims = 2:10)
    sobj <- FindClusters(sobj)
  })
```


```{r, fig.width=5}
1:2 %>% 
  lapply(function(i) {
    DimPlot(sobjs[[i]], label = TRUE) + NoLegend() +
      ggtitle(glue("Pool {i}"))
  })
```

```{r, fig.width=8}
1:2 %>% 
  lapply(function(i) {
    sobjs[[i]]@meta.data %>% 
      count(seurat_clusters, primary_sample) %>% 
      group_by(seurat_clusters) %>% 
      mutate(frac = n / sum(n)) %>% 
      ungroup() %>% 
      ggplot(aes(x = seurat_clusters, y = frac, fill = primary_sample)) +
      geom_col() +
      scale_fill_brewer(palette = "Set1") +
      labs(x = "Cluster", y = "Fraction", fill = "Sample") +
      ggtitle(glue("Pool {i}"))
  })
```


```{r, fig.width=5}
1:2 %>% 
  lapply(function(i) {
    DimPlot(sobjs[[i]], group.by = "demuxlet_call") +
      ggtitle(glue("Pool {i}")) 
  })

1:2 %>% 
  lapply(function(i) {
    DimPlot(sobjs[[i]], group.by = "primary_sample") +
      ggtitle(glue("Pool {i}")) 
  })
```

```{r, fig.width=6, fig.height=6}
1:2 %>% 
  lapply(function(i) {
    DimPlot(sobjs[[i]], group.by = "primary_sample", ) +
      ggtitle(glue("Pool {i}")) +
      facet_wrap(~ primary_sample) +
      NoLegend()
  })
```

```{r, fig.height=6, fig.width=20}
marker_genes <- list(
  OPCs = c(
    'TNR','PDGFRA', 'CNTN1',
    "LHFPL3", "PCDH15"
    ),
  Oligos = c(
    'QDPR','TULP4','PIP4K2A','TMEM144','SLC44A1','CNP','SLAIN1','ANLN','MOBP',
    'SCD','CNDP1','MBP','ERMN','CLDND1','UGT8','TTLL7','SLC24A2','ENPP2','TF',
    'PLP1',
    "MOG",'OPALIN','SEPT4'
    ), 
  Neurons = c(  
    'PCLO','GABRA1','SCG2','UCHL1','GABRB2','GAD1','VSNL1','STMN2','RTN1',
    'SNAP25','SYT1','SCN2A','DLX6-AS1','SYNPR',
    'CNR1','RELN'
    ), 
  Neurons_exc = c(
    "RALYL", "KCNIP4", "CBLN2", "LDB2", "KCNQ5", "SATB2"
    # "SCL17A7"  Not present in the 67-brain data 
  ),
  Neurons_inh = c(
    "NXPH1", "GRIK1", "ADARB2", "GAD2"
    # "LHFPL3", "PCDH15" These are more OPC https://doi.org/10.1016/j.cell.2020.06.027
  ),
  Microglia = c(
    'C3','CCL4','MSR1','OLR1','GPR183','CD53','LCP1','HAVCR2','LHFPL2','PLEK',
    'HLA-DRA','CD74','CX3CR1','C3AR1','CLEC7A','B3GNT5',
    'CD83','IL1B','CH25H',
    "CSF1R", "P2RY12"
    ),
  Endothelial = c(
    'NET1','FN1','APOLD1','TM4SF1','ABCG2','RGS5','DCN',
    "VWF"
  ),
  Astrocytes = c(
    'SLCO1C1','ATP1B2','CPE','AQP4','EDNRB','SLC4A4','GJA1','SLC1A2','CLU',
    'ETNPPL','F3','RYR3',
    'DIO2','GPR37L1',
    "PDGFRA", # Also in OPCs
    "CSPG4", "GFAP"
  )
)



DotPlot(sobjs[[1]], features = unlist(marker_genes) %>% unique(), col.min = 0) + 
  RotatedAxis() +
  ggtitle("Pool1")

DotPlot(sobjs[[2]], features = unlist(marker_genes) %>% unique(), col.min = 0) + 
  RotatedAxis() +
  ggtitle("Pool2")
```

```{r, fig.height=6, fig.width=7}
marker_genes %>% 
  names() %>% 
  lapply(function(i) {
    DotPlot(sobjs[[1]], features = marker_genes[[i]], col.min = 0) + 
      RotatedAxis() +
      ggtitle(glue("Pool1: {i}"))    
  })
```

```{r}
clus_ids <- sobjs[[1]]@meta.data$seurat_clusters %>% as.character()
sobjs[[1]]@meta.data$celltypes <- case_when(
  clus_ids %in% as.character(15) ~ "OPC",
  clus_ids %in% as.character(c(6, 8)) ~ "Oligos", 
  clus_ids %in% as.character(c(0:5, 10:11, 13)) ~ "Neuron_exc",
  clus_ids %in% as.character(c(7, 9, 15, 16)) ~ "Neuron_inh",
  clus_ids %in% as.character(c(14)) ~ "MG-Endo", 
  clus_ids %in% as.character(c(17)) ~ "MG", 
  clus_ids %in% as.character(c(18, 12)) ~ "Astro", 
  T ~ clus_ids
)
```

```{r, fig.height=6, fig.width=7}
marker_genes %>% 
  names() %>% 
  lapply(function(i) { 
    DotPlot(sobjs[[2]], features = marker_genes[[i]], col.min = 0) + 
      RotatedAxis() +
      ggtitle(glue("Pool2: {i}"))    
  })
```

```{r}
clus_ids <- sobjs[[2]]@meta.data$seurat_clusters %>% as.character()
sobjs[[2]]@meta.data$celltypes <- case_when(
  clus_ids %in% as.character(16) ~ "OPC",
  clus_ids %in% as.character(c(0, 1, 8, 13)) ~ "Oligos", 
  clus_ids %in% as.character(c(2:6, 9, 10)) ~ "Neuron_exc",
  clus_ids %in% as.character(c(7, 12, 16, 17)) ~ "Neuron_inh",
  clus_ids %in% as.character(c(18)) ~ "MG", 
  clus_ids %in% as.character(c(19)) ~ "Endo", 
  clus_ids %in% as.character(c(11, 15)) ~ "Astro", 
  T ~ clus_ids
)
```

```{r, fig.width=5}
1:2 %>% 
  lapply(function(i) {
    sobj <- sobjs[[i]]
    Idents(sobj) <- "celltypes"
    DimPlot(sobj, label = TRUE) + NoLegend() +
      ggtitle(glue("Pool {i}"))
  })
```